name: Django CI  # Name of the workflow

# When should this workflow run?
on:
  push:
    branches: [ master ]        # Run on push to master branch
  pull_request:
    branches: [ master ]        # Run on pull requests targeting master

jobs:
  test:                         # Job name
    runs-on: ubuntu-latest      # The virtual environment

    steps:
    - name: Check out code      # Step 1: Get your code from GitHub
      uses: actions/checkout@v3

    - name: Set up Python       # Step 2: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # You can change this to your version

    - name: Install dependencies  # Step 3: Install your Django project requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations        # Step 4: Prepare the database (SQLite)
      run: python manage.py migrate

    - name: Run tests             # Step 5: Run tests (we created a dummy one earlier)
      run: python manage.py test
